name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - '1.2'  # minimum version that goveralls supports
          - '1.10' # last version that doesn't support go modules
          - '1.11' # first version that supports go modules
          - '1.x'  # latest version
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin $GITHUB_HEAD_REF

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go version

      - name: Set up the action
        run: |
          make all      # build goveralls binaries
          npm ci        # install node modules
          npm run build # build JavaScript
      - run: npm test

      - run: go test -v -coverprofile=profile.cov ./...
      - name: send coverage
        uses: ./
        with:
          path-to-profile: profile.cov
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.x"
      - name: Set up the action
        run: |
          make all      # build goveralls binaries
          npm ci        # install node modules
          npm run build # build JavaScript
      - name: finalize parallel build
        uses: ./
        with: 
          parallel-finished: true
