name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: "1.x"
    - run: make all
    - run: make test

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-profile: profile.cov
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: "1.x"
    - run: make all

    - run: npm run build
    - uses: ./
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
